# FROM php:8.2-fpm

# RUN pecl install redis && \
#     docker-php-ext-enable redis && \
#     docker-php-ext-install mysqli && \
#     echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini
FROM php:8.2-fpm

# Install PHP extensions
RUN pecl install redis && \
    docker-php-ext-install mysqli && \
    docker-php-ext-enable mysqli

# Set the working directory inside the container
WORKDIR /var/www/html

# Copy the application source files into the image
COPY ../ /var/www/html/